#!/bin/sh
testfile="$1"
output=$(cat)
awk '/CHECK:/{sub(/.*CHECK:[[:space:]]*/, "", $0); print}' "$testfile" | while IFS= read -r expected; do
	printf "%s" "$output" | grep -F -- "$expected" >/dev/null 2>&1 || {
		echo "tinl-check: missing pattern: $expected" >&2
		exit 1
	}
done
exit 0
